#!/usr/bin/env python3
"""Seed 10 demo houses with all spec fields filled (Perm region).

Usage:
  poetry run python scripts/seed_houses.py
  poetry run python scripts/seed_houses.py --reset   # truncate houses first
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from decimal import Decimal
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from config.settings import Settings  # noqa: E402
from domain.entities.house_write import HouseWriteData  # noqa: E402
from domain.enums.house import (  # noqa: E402
    GasType,
    LandCategory,
    ObjectType,
    ParkingType,
    Readiness,
    Renovation,
    RoofMaterial,
    SewageType,
    UtilityLevel,
    WallMaterial,
    WaterSupplyType,
)
from infrastructure.db.database import Database  # noqa: E402
from infrastructure.repositories.alchemy.house_model import SqlAlchemyHouseRepository  # noqa: E402
from sqlalchemy import text  # noqa: E402

PERM = (Decimal("58.010500"), Decimal("56.250200"))


def house(
    *,
    name: str,
    description: str,
    location: str,
    address: str,
    lat_offset: float,
    lon_offset: float,
    area_sqm: int | None,
    sort_order: int,
    object_type: ObjectType,
    readiness: Readiness,
    land_category: LandCategory,
    build_year: int,
    wall_material: WallMaterial,
    roof_material: RoofMaterial,
    floors_count: int,
    rooms_count: int,
    plot_area_sotka: str,
    price_rub: int,
    cadastral_number: str,
    distance_to_city_km: str,
    ceiling_height_m: str,
    renovation: Renovation,
    parking: ParkingType,
    gas: GasType,
    water_supply: WaterSupplyType,
    sewage: SewageType,
    flags: dict[str, bool],
) -> HouseWriteData:
    lat, lon = PERM
    return HouseWriteData(
        name=name,
        description=description,
        location=location,
        area_sqm=area_sqm,
        is_published=True,
        sort_order=sort_order,
        address=address,
        latitude=lat + Decimal(str(lat_offset)),
        longitude=lon + Decimal(str(lon_offset)),
        object_type=object_type.value,
        readiness=readiness.value,
        land_category=land_category.value,
        build_year=build_year,
        wall_material=wall_material.value,
        roof_material=roof_material.value,
        floors_count=floors_count,
        rooms_count=rooms_count,
        plot_area_sotka=Decimal(plot_area_sotka),
        price_rub=price_rub,
        cadastral_number=cadastral_number,
        distance_to_city_km=Decimal(distance_to_city_km),
        ceiling_height_m=Decimal(ceiling_height_m),
        renovation=renovation.value,
        parking=parking.value,
        electricity=UtilityLevel.YES.value,
        gas=gas.value,
        heating=UtilityLevel.YES.value,
        water_supply=water_supply.value,
        sewage=sewage.value,
        has_bathhouse=flags.get("has_bathhouse", False),
        has_pool=flags.get("has_pool", False),
        has_terrace=flags.get("has_terrace", False),
        bathroom_in_house=flags.get("bathroom_in_house", True),
        bathroom_outside=flags.get("bathroom_outside", False),
        has_wifi=flags.get("has_wifi", True),
        has_tv=flags.get("has_tv", True),
        transport_asphalt=flags.get("transport_asphalt", True),
        transport_public_stop=flags.get("transport_public_stop", False),
        transport_railway=flags.get("transport_railway", False),
        infra_shop=flags.get("infra_shop", False),
        infra_pharmacy=flags.get("infra_pharmacy", False),
        infra_kindergarten=flags.get("infra_kindergarten", False),
        infra_school=flags.get("infra_school", False),
        is_mortgage_available=flags.get("is_mortgage_available", True),
        is_share_sale=flags.get("is_share_sale", False),
        is_auction=flags.get("is_auction", False),
        has_fence=flags.get("has_fence", True),
        has_security=flags.get("has_security", False),
    )


HOUSES: list[HouseWriteData] = [
    house(
        name="Резиденция «Гайва Парк»",
        description="Кирпичный дом с террасой и баней. Тихий район, асфальт до ворот, центральные коммуникации.",
        location="Пермский край, Пермь",
        address="Пермь, 3-й Гайвинский переулок, 11",
        lat_offset=0.012,
        lon_offset=-0.018,
        area_sqm=142,
        sort_order=1,
        object_type=ObjectType.HOUSE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.IZHS,
        build_year=2018,
        wall_material=WallMaterial.BRICK,
        roof_material=RoofMaterial.METAL,
        floors_count=2,
        rooms_count=5,
        plot_area_sotka="12.5",
        price_rub=18_500_000,
        cadastral_number="59:01:0010101:123",
        distance_to_city_km="8.0",
        ceiling_height_m="3.10",
        renovation=Renovation.EURO,
        parking=ParkingType.GARAGE,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.CENTRAL,
        flags={
            "has_bathhouse": True,
            "has_terrace": True,
            "transport_public_stop": True,
            "infra_shop": True,
            "infra_pharmacy": True,
            "has_security": True,
        },
    ),
    house(
        name="Дача «Кама берег»",
        description="Уютная дача для сезонного отдыха. Скважина, септик, газ по границе участка.",
        location="Пермский край, Краснокамский район",
        address="Краснокамск, ул. Лесная, 24",
        lat_offset=0.045,
        lon_offset=0.032,
        area_sqm=68,
        sort_order=2,
        object_type=ObjectType.DACHA,
        readiness=Readiness.BUILT,
        land_category=LandCategory.SNT,
        build_year=2005,
        wall_material=WallMaterial.WOOD,
        roof_material=RoofMaterial.SOFT,
        floors_count=1,
        rooms_count=3,
        plot_area_sotka="6.0",
        price_rub=4_200_000,
        cadastral_number="59:02:0020202:456",
        distance_to_city_km="22.0",
        ceiling_height_m="2.65",
        renovation=Renovation.COSMETIC,
        parking=ParkingType.PARKING_SPOT,
        gas=GasType.AT_BOUNDARY,
        water_supply=WaterSupplyType.BOREHOLE,
        sewage=SewageType.SEPTIC,
        flags={
            "has_bathhouse": True,
            "bathroom_outside": True,
            "transport_railway": True,
            "infra_shop": True,
        },
    ),
    house(
        name="Коттедж «Сосновый бор»",
        description="Каркасный коттедж под ключ. Бассейн, дизайнерский ремонт, охраняемая территория.",
        location="Пермский край, Пермь",
        address="Пермь, ул. Сосновая, 7",
        lat_offset=-0.008,
        lon_offset=0.021,
        area_sqm=210,
        sort_order=3,
        object_type=ObjectType.COTTAGE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.DNP,
        build_year=2021,
        wall_material=WallMaterial.FRAME,
        roof_material=RoofMaterial.TILE,
        floors_count=2,
        rooms_count=6,
        plot_area_sotka="15.0",
        price_rub=32_000_000,
        cadastral_number="59:01:0030303:789",
        distance_to_city_km="5.5",
        ceiling_height_m="3.40",
        renovation=Renovation.DESIGNER,
        parking=ParkingType.GARAGE,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.BIO_STATION,
        flags={
            "has_pool": True,
            "has_terrace": True,
            "has_security": True,
            "infra_kindergarten": True,
            "infra_school": True,
        },
    ),
    house(
        name="Таунхаус «Центральный»",
        description="Трёхэтажный таунхаус в черте города. Пешая доступность к остановке и школе.",
        location="Пермский край, Пермь",
        address="Пермь, ул. Ленина, 102",
        lat_offset=0.002,
        lon_offset=-0.005,
        area_sqm=118,
        sort_order=4,
        object_type=ObjectType.TOWNHOUSE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.IZHS,
        build_year=2015,
        wall_material=WallMaterial.BLOCK,
        roof_material=RoofMaterial.METAL,
        floors_count=3,
        rooms_count=4,
        plot_area_sotka="2.8",
        price_rub=12_800_000,
        cadastral_number="59:01:0040404:101",
        distance_to_city_km="0.0",
        ceiling_height_m="2.90",
        renovation=Renovation.EURO,
        parking=ParkingType.PARKING_SPOT,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.CENTRAL,
        flags={
            "transport_public_stop": True,
            "infra_pharmacy": True,
            "infra_school": True,
            "is_share_sale": True,
        },
    ),
    house(
        name="Дом «Муллы холм»",
        description="Монолитный дом на возвышенности с панорамными окнами. Требует финальной отделки.",
        location="Пермский край, Пермь",
        address="Пермь, ул. Муллинская, 45",
        lat_offset=-0.015,
        lon_offset=-0.012,
        area_sqm=185,
        sort_order=5,
        object_type=ObjectType.HOUSE,
        readiness=Readiness.UNFINISHED,
        land_category=LandCategory.IZHS,
        build_year=2024,
        wall_material=WallMaterial.MONOLITH,
        roof_material=RoofMaterial.SOFT,
        floors_count=2,
        rooms_count=5,
        plot_area_sotka="10.0",
        price_rub=15_900_000,
        cadastral_number="59:01:0050505:202",
        distance_to_city_km="6.0",
        ceiling_height_m="3.00",
        renovation=Renovation.REQUIRED,
        parking=ParkingType.GARAGE,
        gas=GasType.AT_BOUNDARY,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.SEPTIC,
        flags={
            "has_terrace": True,
            "transport_asphalt": True,
            "infra_shop": True,
        },
    ),
    house(
        name="Проект «Заказной усадьба»",
        description="Участок ИЖС под индивидуальный проект. Готовы построить дом по вашему эскизу.",
        location="Пермский край, Пермский район",
        address="д. Ферма, ул. Полевая, 3",
        lat_offset=0.028,
        lon_offset=-0.035,
        area_sqm=None,
        sort_order=6,
        object_type=ObjectType.HOUSE,
        readiness=Readiness.CUSTOM_BUILD,
        land_category=LandCategory.LPH,
        build_year=2026,
        wall_material=WallMaterial.OTHER,
        roof_material=RoofMaterial.OTHER,
        floors_count=2,
        rooms_count=4,
        plot_area_sotka="20.0",
        price_rub=3_500_000,
        cadastral_number="59:03:0060606:303",
        distance_to_city_km="18.0",
        ceiling_height_m="2.80",
        renovation=Renovation.REQUIRED,
        parking=ParkingType.PARKING_SPOT,
        gas=GasType.AT_BOUNDARY,
        water_supply=WaterSupplyType.WELL,
        sewage=SewageType.CESSPOOL,
        flags={
            "is_auction": True,
            "has_fence": True,
        },
    ),
    house(
        name="Усадьба «Протасово»",
        description="Большой дом на сельхоз землях с баней и бассейном. Идеал для большой семьи.",
        location="Пермский край, Пермский район",
        address="с. Протасово, ул. Центральная, 18",
        lat_offset=0.055,
        lon_offset=0.048,
        area_sqm=240,
        sort_order=7,
        object_type=ObjectType.HOUSE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.AGRICULTURAL,
        build_year=2010,
        wall_material=WallMaterial.BRICK,
        roof_material=RoofMaterial.TILE,
        floors_count=2,
        rooms_count=7,
        plot_area_sotka="25.0",
        price_rub=28_500_000,
        cadastral_number="59:03:0070707:404",
        distance_to_city_km="25.0",
        ceiling_height_m="3.20",
        renovation=Renovation.COSMETIC,
        parking=ParkingType.GARAGE,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.BOREHOLE,
        sewage=SewageType.SEPTIC,
        flags={
            "has_bathhouse": True,
            "has_pool": True,
            "bathroom_outside": True,
            "transport_railway": True,
            "infra_shop": True,
            "infra_pharmacy": True,
        },
    ),
    house(
        name="Дом «Новые Ляды»",
        description="Современный блок-дом в спальном районе. Wi‑Fi, ТВ, детский сад рядом.",
        location="Пермский край, Пермь",
        address="Пермь, ул. Новые Ляды, 33",
        lat_offset=-0.022,
        lon_offset=0.015,
        area_sqm=95,
        sort_order=8,
        object_type=ObjectType.HOUSE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.IZHS,
        build_year=2019,
        wall_material=WallMaterial.BLOCK,
        roof_material=RoofMaterial.METAL,
        floors_count=1,
        rooms_count=4,
        plot_area_sotka="8.5",
        price_rub=9_750_000,
        cadastral_number="59:01:0080808:505",
        distance_to_city_km="4.0",
        ceiling_height_m="2.75",
        renovation=Renovation.EURO,
        parking=ParkingType.PARKING_SPOT,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.CENTRAL,
        flags={
            "has_terrace": True,
            "transport_public_stop": True,
            "infra_kindergarten": True,
            "is_mortgage_available": True,
        },
    ),
    house(
        name="Дача «Вычегда»",
        description="Компактная дача у реки. Колодец, выгребная яма, лес рядом.",
        location="Пермский край, Пермский район",
        address="д. Мысы, ул. Речная, 5",
        lat_offset=0.038,
        lon_offset=-0.042,
        area_sqm=52,
        sort_order=9,
        object_type=ObjectType.DACHA,
        readiness=Readiness.BUILT,
        land_category=LandCategory.SNT,
        build_year=1998,
        wall_material=WallMaterial.WOOD,
        roof_material=RoofMaterial.OTHER,
        floors_count=1,
        rooms_count=2,
        plot_area_sotka="4.5",
        price_rub=2_850_000,
        cadastral_number="59:03:0090909:606",
        distance_to_city_km="30.0",
        ceiling_height_m="2.50",
        renovation=Renovation.REQUIRED,
        parking=ParkingType.PARKING_SPOT,
        gas=GasType.NONE,
        water_supply=WaterSupplyType.WELL,
        sewage=SewageType.CESSPOOL,
        flags={
            "bathroom_outside": True,
            "has_wifi": False,
            "transport_asphalt": True,
        },
    ),
    house(
        name="Коттедж «Кунгурская»",
        description="Премиальный коттедж с охраной и аукционной продажей. Все коммуникации, бассейн, баня.",
        location="Пермский край, Пермь",
        address="Пермь, ул. Кунгурская, 88",
        lat_offset=-0.005,
        lon_offset=0.038,
        area_sqm=320,
        sort_order=10,
        object_type=ObjectType.COTTAGE,
        readiness=Readiness.BUILT,
        land_category=LandCategory.OTHER,
        build_year=2022,
        wall_material=WallMaterial.MONOLITH,
        roof_material=RoofMaterial.TILE,
        floors_count=3,
        rooms_count=8,
        plot_area_sotka="18.0",
        price_rub=45_000_000,
        cadastral_number="59:01:0101010:707",
        distance_to_city_km="3.0",
        ceiling_height_m="3.50",
        renovation=Renovation.DESIGNER,
        parking=ParkingType.GARAGE,
        gas=GasType.IN_HOUSE,
        water_supply=WaterSupplyType.CENTRAL,
        sewage=SewageType.BIO_STATION,
        flags={
            "has_bathhouse": True,
            "has_pool": True,
            "has_terrace": True,
            "has_security": True,
            "transport_public_stop": True,
            "infra_shop": True,
            "infra_pharmacy": True,
            "infra_kindergarten": True,
            "infra_school": True,
            "is_auction": True,
            "is_mortgage_available": True,
        },
    ),
]


async def main() -> None:
    parser = argparse.ArgumentParser(description="Seed demo houses")
    parser.add_argument("--reset", action="store_true", help="Delete all houses before seeding")
    args = parser.parse_args()

    settings = Settings()
    db = Database(settings)

    async with db.session_factory() as session:
        if args.reset:
            await session.execute(text("TRUNCATE houses RESTART IDENTITY CASCADE"))
            print("houses truncated")

        repo = SqlAlchemyHouseRepository(session)
        for data in HOUSES:
            entity = await repo.create(data)
            print(f"+ {entity.name}  {entity.id}")

        await session.commit()

    await db.dispose()
    print(f"Done: {len(HOUSES)} houses")


if __name__ == "__main__":
    asyncio.run(main())
