from domain.entities.house_write import HouseWriteData


def house_write_values(data: HouseWriteData) -> dict:
    return {
        "name": data.name,
        "description": data.description,
        "location": data.location,
        "area_sqm": data.area_sqm,
        "is_published": data.is_published,
        "sort_order": data.sort_order,
        "address": data.address,
        "latitude": data.latitude,
        "longitude": data.longitude,
        "object_type": data.object_type,
        "readiness": data.readiness,
        "land_category": data.land_category,
        "build_year": data.build_year,
        "wall_material": data.wall_material,
        "roof_material": data.roof_material,
        "floors_count": data.floors_count,
        "rooms_count": data.rooms_count,
        "plot_area_sotka": data.plot_area_sotka,
        "price_rub": data.price_rub,
        "cadastral_number": data.cadastral_number,
        "distance_to_city_km": data.distance_to_city_km,
        "ceiling_height_m": data.ceiling_height_m,
        "renovation": data.renovation,
        "parking": data.parking,
        "electricity": data.electricity,
        "gas": data.gas,
        "heating": data.heating,
        "water_supply": data.water_supply,
        "sewage": data.sewage,
        "has_bathhouse": data.has_bathhouse,
        "has_pool": data.has_pool,
        "has_terrace": data.has_terrace,
        "bathroom_in_house": data.bathroom_in_house,
        "bathroom_outside": data.bathroom_outside,
        "has_wifi": data.has_wifi,
        "has_tv": data.has_tv,
        "transport_asphalt": data.transport_asphalt,
        "transport_public_stop": data.transport_public_stop,
        "transport_railway": data.transport_railway,
        "infra_shop": data.infra_shop,
        "infra_pharmacy": data.infra_pharmacy,
        "infra_kindergarten": data.infra_kindergarten,
        "infra_school": data.infra_school,
        "is_mortgage_available": data.is_mortgage_available,
        "is_share_sale": data.is_share_sale,
        "is_auction": data.is_auction,
        "has_fence": data.has_fence,
        "has_security": data.has_security,
    }
