// Auto-generated by scripts/sync-glb-manifest.mjs — do not edit by hand.
// Add .glb files to public/models/ and run: npm run sync:models

export interface GlbModel {
  id: string
  name: string
  description: string
  glb: string
}

export const models: GlbModel[] = [
  {
    "id": "1ggp03-tom-pauwaert-english-cottage-diorama",
    "name": "1ggp03 Tom Pauwaert English Cottage Diorama",
    "description": "3D-модель «1ggp03 Tom Pauwaert English Cottage Diorama» (.glb).",
    "glb": "/models/1ggp03_tom_pauwaert_-_english_cottage_diorama.glb"
  },
  {
    "id": "2-bedroom-cottage",
    "name": "2 Bedroom Cottage",
    "description": "3D-модель «2 Bedroom Cottage» (.glb).",
    "glb": "/models/2_bedroom_cottage.glb"
  },
  {
    "id": "cottage-free-blender",
    "name": "Cottage Free Blender",
    "description": "3D-модель «Cottage Free Blender» (.glb).",
    "glb": "/models/cottage-free_blender.glb"
  },
  {
    "id": "day4-the-cottage",
    "name": "Day4 The Cottage",
    "description": "3D-модель «Day4 The Cottage» (.glb).",
    "glb": "/models/day4_the_cottage.glb"
  },
  {
    "id": "demo-house",
    "name": "Демо-проект",
    "description": "Пример .glb модели коттеджа.",
    "glb": "/models/demo-house.glb"
  },
  {
    "id": "house-stone-cabin-modern-log-cabin-03",
    "name": "House Stone Cabin Modern Log Cabin 03",
    "description": "3D-модель «House Stone Cabin Modern Log Cabin 03» (.glb).",
    "glb": "/models/house_-_stone_cabin_-_modern_log_cabin_03.glb"
  },
  {
    "id": "oriental-building",
    "name": "Oriental Building",
    "description": "3D-модель «Oriental Building» (.glb).",
    "glb": "/models/oriental_building.glb"
  },
  {
    "id": "small-brick-house",
    "name": "Small Brick House",
    "description": "3D-модель «Small Brick House» (.glb).",
    "glb": "/models/small_brick_house.glb"
  },
  {
    "id": "swedish-cottage-diorama",
    "name": "Swedish Cottage Diorama",
    "description": "3D-модель шведского коттеджа.",
    "glb": "/models/swedish_cottage_diorama.glb"
  },
  {
    "id": "white-silver-green-residence",
    "name": "White Silver Green Residence",
    "description": "3D-модель «White Silver Green Residence» (.glb).",
    "glb": "/models/white_silver_green_residence.glb"
  }
]
